### ISSUE TITLE
How to activate a new user?

### ISSUE THREAD

**Issue by mjllewelyn** [EnVisageConsulting/timelog#25]
This is more of a question. I made a new user, but how do I set their password and activate them. I would have assumed it was on the user new/edit form, but it wasn't. Also the new user is only showing up on the manage users list, they aren't showing up on any other list, so they can't log in until was seems to me that they have a password

**Comment by dhuey** [comment]
My guess is that it'll be associated with #12 ... I think the general flow would be to add a user, user gets an email, user clicks a link to activate and set their password, then user can login.

I would probably set this as a lower priority than reports, emails, etc., since we don't have to add users too often and we can always add them through the console. We'll want to fill out that functionality at some point, but I don't think it's totally required for us to get this up and running.
