### ISSUE TITLE
Finish Current Log time doesn't update

### ISSUE THREAD

**Issue by agaug** [EnVisageConsulting/timelog#44]
I was testing the timelog and the "Finish Current Log" doesn't update to match the time in the start date. Here is an image

![image](https://user-images.githubusercontent.com/33165589/77930731-dee9f680-7270-11ea-8826-7dd935145685.png)

Since the picture is a little small, here are the important numbers:
1. Finish Current Log 00h 23m 29 s
2. Start date 03/30/2020 10:14 AM 
3. Actual time: 10:24 AM

I created a previous log that ended at 10:16 (ish) and so that was the time that the "Finish Current Log" was set to. When I manually fixed the start date (to be no. 2) the "Finish Current Log" time didn't update. Is there a way to make it so that the time in no. 1 to pull from the time posted in no. 2?

Here's a link http://ectimelog.herokuapp.com/logs/462/edit

**Comment by dhuey** [comment]
I would check if the Finish Current Log time doesn't update when you change the start time and then click to a different page.

I don't think it would be super important for us to update the Finish Current Log time as you make changes on the Edit Log page. Because in one sense, you're in the process of "finishing the current log," which could involve changing the start time. And when you're working on it, the Finish Current Log counter isn't really important to you.

I would maybe even consider disabling the counter on the Edit Log page.

**Comment by dhuey** [comment]
This was fixed in the last commit on #50
