### ISSUE TITLE
Find a way to import access db data

### ISSUE THREAD

**Issue by dhuey** [EnVisageConsulting/timelog#48]
From Connie:
"It's going to have to line up with both a pay period and the end of a month when we do a clean switchover.  Since those two things don't line up well, there will have to be some data from the access database imported into the online timelog.  Is there a way to either copy over or import a period of data that won't take too much work?"

We'll need to figure out what an export of data looks like and see if there's a way we can make it line up correctly with our PostgreSQL db. It also might be easier to just have people double-enter their own time in both the timelog and the access db

**Comment by mjllewelyn** [comment]
I took a look at this. It looks like the access db can be exported to another format, such as an Excel file and then the columns could be rearranged on that to import it into the timelog

**Comment by dhuey** [comment]
I think that sounds like a viable solution, though we'll have to be sure we edit it all correctly and get it imported. I would assume if we have something in CSV, we could probably copy/paste into PSequel and call it good.

**Comment by mjllewelyn** [comment]
Dalton and I talked about this and it seems like the best way would be just to double enter until we can fully switch over. The problem comes because there are two db tables in the online timelog, but only one for the access db. Also we'd have to figure out each person's id to have it be entered into the online db. So there would have to be quite a bit of data manipulation to get it copied over in the exact same format which would take quite a bit of time.
